### ISSUE TITLE
Sharded pub/sub suport in `RedisClient::Cluster::PubSub`

### ISSUE THREAD

**Issue by slai11** [redis-rb/redis-cluster-client#214]
### Problem

I was trying to add support for Redis 7's sharded pub/sub in `redis/redis-rb` but I noticed that `RedisClient::Cluster::PubSub` would [perform](https://github.com/redis-rb/redis-cluster-client/blob/master/lib/redis_client/cluster/pub_sub.rb#L13) `.close` before each `call/call_v` and runs `.next_event` on 1 `RedisClient::PubSub` at a time. This prevents the user from adding additional subscriptions since the previous `RedisClient::PubSub` would close. 

The workaround for regular pub/sub via `SUBSCRIBE` or `PSUBSCRIBE` would be to maintain an array of subscribed channels and just re-subscribe to them. i.e. `redis.call(['subscribe', 'chanA', 'chanB'])` instead of `redis.call(['subscribe', 'chanA'])` and `redis.call(['subscribe', 'chanB'])` separately. 

### Lack of support for sharded pub/sub

While this works for standard pub/sub commands, sharded pub/sub will not work since the keys are mapped to a particular shard channel which means you cannot subscribe to all channels via 1 connection.

### Proposal

This lead me to think that for truly sharded pub/sub, `RedisClient::Cluster::PubSub` will need to maintain up to 1 `RedisClient::PubSub` per shard. Either that or let the caller manage the `RedisClient::PubSub` connections which bypass `redis-cluster-client`.

I have drafted a commit for the `1 RedisClient::PubSub per shard` approach on my fork https://github.com/slai11/redis-cluster-client/commit/4d401da3cf3fa8ff2853c53e9cb0b4424731d073 if that helps better explain things.

I'm not sure if the maintainers have a roadmap for sharded pub/sub (or if I'm going the wrong way about this). Would love to get your feedback and possibly help out 👍

**Comment by supercaracal** [comment]
I think the issue is similar to restrict for MSET, MGET commands with cluster mode.  We can transform MSET, MGET commands to pipelining like converting horizontal into vertical.

Channels for sharded Pub/Sub are also restricted by same slot. But we can't use pipelining way for Pub/Sub. Although we can create a new pubsub instance per subscribe channels.

https://github.com/redis-rb/redis-cluster-client/blob/b24e528f12b3d5918207a2c5364a3e25fad36b44/test/redis_client/test_cluster.rb#L205-L225

Would you give me some time to look into it?

**Comment by supercaracal** [comment]
I apologize for my bad implementation. Redis document says:

> All the specified shard channels needs to belong to a single slot to subscribe in a given SSUBSCRIBE call, A client can subscribe to channels across different slots over separate SSUBSCRIBE call.

https://redis.io/commands/ssubscribe/

So I fixed the code to be able to subscribe multiple channels. Let me know if there are more bugs related to Pub/Sub.

**Comment by supercaracal** [comment]
https://rubygems.org/gems/redis-cluster-client/versions/0.4.5

**Comment by supercaracal** [comment]
https://rubygems.org/gems/redis-cluster-client/versions/0.4.6

**Comment by slai11** [comment]
@supercaracal thank you for your speedy response!

I noticed that the current implementation would block if the timeout is set to 0 since it is a [blocking read](https://github.com/redis-rb/redis-client/blob/68dbe6b27d259f29af099128fe6ad83193160253/lib/redis_client/ruby_connection/buffered_io.rb#L44). 

This would mean all threads need to complete before `collect_messages` would return. That would require all `pubsub.next_event(timeout)` in `pubsub_states` to receive a message rather than exiting on the first message (https://github.com/redis-rb/redis-cluster-client/blob/c72a3d384d0e74250ef3a075303d2a9c3f709b12/lib/redis_client/cluster/pub_sub.rb#L53).

I faced this problem while drafting a possible fix, hence in my draft https://github.com/slai11/redis-cluster-client/commit/4d401da3cf3fa8ff2853c53e9cb0b4424731d073 I used a `Monitor` but there is some code smell as it does not wait for all threads to terminate (instead letting them run in the background until they timeout or receive a message).

```
# connect to a local cluster, ports may differ
client = RedisClient.cluster(nodes: %w[redis://localhost:7101 redis://localhost:7001 redis://localhost:7201]).new_client

ps = client.pubsub

# subscribe to a bunch of channels
['channelA', 'channelB', 'channelC', 'channelD'].each { |c| ps.call('ssubscribe', c)}

# loop the subscription
loop do
  puts ps.next_event(0)
end

# outputs only 3 ssubscribe, blocks on 4th
ssubscribe
channelA
1
ssubscribe
channelB
1
ssubscribe
channelD
1

```

The above snippet outputs only 1 message from each `pubsub` and blocks on the 4th message since the other 2 `pubsub` instances are waiting for messages. To support this behaviour, try sending `SPUBLISH` messages to `channelA` and `channelD` (they should be on separate nodes). 


Another point is that timeout is multiplied by MAX_THREADS. i.e. if there are 10 shards and MAXTHREAD is 5, it would run 2 iterations of the loop with the same timeout value. So if `pubsub.timeout(1)` is run, it would wait 2 seconds instead of 1 since it would wait for 1 second on the first slice, and 1 second on the second slice. 

I'm wondering if we could use `timeout/(@pubsub_states.size / MAX_THREADS)` as the timeout for each inner `.next_event` call 🤔

**Comment by supercaracal** [comment]
Sorry, it's exactly as you said. It seems that the official gem's CI was failed with job's deadline exceeded. I'll fix that stupid behavior.

**Comment by supercaracal** [comment]
https://rubygems.org/gems/redis-cluster-client/versions/0.4.7

**Comment by supercaracal** [comment]
I've fixed a bit to prevent subscription bias.
https://rubygems.org/gems/redis-cluster-client/versions/0.4.8
