### ISSUE TITLE
Support configuration option that allows the use of the original client configuration when refreshing nodes

### ISSUE THREAD

**Issue by learoyklinginsmith** [redis-rb/redis-cluster-client#291]
### Problem

When using a DNS endpoint and all of the underlying host IPs are changed, this can cause continuous connection errors, as the node list is fetched during initialization and then not refreshed from the original DNS endpoint. We've had this happen during Elasticache maintenance when all underlying nodes in the clusters are slowly replaced. I don't think this is unique to us and could happen to anyone using Elasticache with cluster mode enabled.

### Potential Solution

Add a configuration option that allows cluster rediscovery using the original configuration options that were passed in. This would allow the original DNS endpoint to be used and the fresh list of nodes gathered, instead of continuing to try to talk to any of the outdated nodes. I've opened a draft [PR](https://github.com/redis-rb/redis-cluster-client/pull/290) that adds this.

Looking forward to hearing your thoughts on this issue and any other potential solutions. Thanks.

**Comment by supercaracal** [comment]
released with 0.7.5

* https://github.com/redis-rb/redis-cluster-client/releases/tag/v0.7.5
* https://rubygems.org/gems/redis-cluster-client/versions/0.7.5

**Comment by praveen-ks** [comment]
I am using single node cluster mode disabled instance of AWS ElastiCache. I am working on upgrading it which will change the underlying IP Address for the endpoint.
I am trying to understand how https://github.com/redis-rb/redis-client/ will behave in that case.

Thanks in advance for any leads.
