### ISSUE TITLE
Implement #pipelined, #multi, #pubsub, #size, #with

### ISSUE THREAD

**Issue by supercaracal** [redis-rb/redis-cluster-client#7]

**Comment by sj26** [comment]
Hi @supercaracal (and @byroot who I see over on redis-client)!

I'm very interested in redis-client and redis-cluster-client. We're wanting to switch to clustered mode redis at @buildkite but finding that redis-rb's restriction on cross-slot pipeline is a blocker:
https://github.com/redis/redis-rb/blob/4724c1bfde2d5679128ced8ec7b46bac66605b7b/lib/redis/cluster.rb#L83-L84

Are you hoping to fix that problem in this gem? Maybe doing something like what redis-py-cluster does?
https://redis-py-cluster.readthedocs.io/en/master/pipelines.html

If so I'd be keen to figure out if we can collaborate. 🙏

**Comment by supercaracal** [comment]
`#pipelined` and `#pubsub` methods were implemented. The others were gotten rid of.

**Comment by supercaracal** [comment]
@sj26 `0.0.3` is out. You can use this if you’d like.

**Comment by sj26** [comment]
Thanks @supercaracal! We'll take a look when we can. 🙏
